# Generated by Django 5.2.5 on 2025-08-11 19:17

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('base_legal', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FonteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Fonte de Recurso',
                'verbose_name_plural': 'Fontes de Recurso',
                'unique_together': {('codigo', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo_adm', models.CharField(max_length=50)),
                ('numero_edital', models.CharField(blank=True, max_length=50)),
                ('ano_referencia', models.PositiveIntegerField()),
                ('objeto', models.TextField()),
                ('escopo_disputa', models.CharField(choices=[('GLOBAL', 'Global'), ('POR_ITEM', 'Por item'), ('POR_LOTE', 'Por lote')], default='POR_ITEM', max_length=15)),
                ('criterio_julgamento', models.CharField(choices=[('MENOR_PRECO', 'Menor preço'), ('MAIOR_DESCONTO', 'Maior desconto'), ('MELHOR_TECNICA', 'Melhor técnica/Conteúdo artístico'), ('TECNICA_E_PRECO', 'Técnica e preço'), ('MAIOR_LANCE', 'Maior lance (leilão)'), ('MAIOR_RETORNO_ECONOMICO', 'Maior retorno econômico')], default='MENOR_PRECO', max_length=30)),
                ('modo_disputa', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('ABERTO_FECHADO', 'Aberto-Fechado'), ('FECHADO_ABERTO', 'Fechado-Aberto')], max_length=20)),
                ('tipo_objeto', models.CharField(choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('OBRA', 'Obra'), ('SERVICO_ENGENHARIA', 'Serviço de Engenharia')], max_length=25)),
                ('tipo_contratacao', models.CharField(choices=[('REGISTRO_PRECOS', 'Registro de Preços'), ('AQUISICAO', 'Aquisição'), ('AQUISICAO_PARCELADA', 'Aquisição parcelada')], default='AQUISICAO', max_length=25)),
                ('dispensa_com_disputa', models.BooleanField(blank=True, help_text='Apenas para Dispensa: marque se haverá disputa.', null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_hora_abertura', models.DateTimeField(blank=True, null=True)),
                ('inicio_recolhimento_propostas', models.DateTimeField(blank=True, null=True)),
                ('fim_recolhimento_propostas', models.DateTimeField(blank=True, null=True)),
                ('fim_impugnacao_esclarecimentos', models.DateTimeField(blank=True, null=True)),
                ('prazo_manifestacao_recurso_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_manifestacao_recurso_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_recebimento_recursos_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_recebimento_recursos_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_contrarrazoes_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_contrarrazoes_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_homologado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autoridade_competente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_como_autoridade', to='core.pessoa')),
                ('condutor_processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_como_condutor', to='core.pessoa')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modalidade')),
            ],
            options={
                'ordering': ['-ano_referencia', 'numero_processo_adm'],
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='core.processo')),
            ],
            options={
                'ordering': ['-data_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalObservacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.processo')),
            ],
            options={
                'verbose_name': 'historical observacao',
                'verbose_name_plural': 'historical observacaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFornecimentoItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('status_item', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('JULGADO', 'Julgado'), ('ADJUDICADO', 'Adjudicado'), ('HOMOLOGADO', 'Homologado'), ('FRACASSADO', 'Fracassado'), ('DESERTO', 'Deserto'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.fornecedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.processo')),
            ],
            options={
                'verbose_name': 'historical fornecimento item',
                'verbose_name_plural': 'historical fornecimento items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCI',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva Orçamentária'), ('PJ', 'Parecer Jurídico'), ('PT', 'Parecer Técnico'), ('OUTROS', 'Outros')], default='OUTROS', max_length=10)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor_referente', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.pessoa')),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.processo')),
            ],
            options={
                'verbose_name': 'historical ci',
                'verbose_name_plural': 'historical cis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.elementodespesa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processo')),
            ],
            options={
                'verbose_name': 'Elemento de Despesa do Processo',
                'verbose_name_plural': 'Elementos de Despesa do Processo',
                'unique_together': {('processo', 'elemento')},
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='elementos_despesa',
            field=models.ManyToManyField(blank=True, related_name='processos', through='core.ProcessoElemento', to='core.elementodespesa'),
        ),
        migrations.CreateModel(
            name='ProcessoFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fonterecurso')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processo')),
            ],
            options={
                'verbose_name': 'Fonte de Recurso do Processo',
                'verbose_name_plural': 'Fontes de Recurso do Processo',
                'unique_together': {('processo', 'fonte')},
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='fontes_recursos',
            field=models.ManyToManyField(blank=True, related_name='processos', through='core.ProcessoFonte', to='core.fonterecurso'),
        ),
        migrations.CreateModel(
            name='ProcessoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.projetoatividade')),
            ],
            options={
                'verbose_name': 'Projeto/Atividade do Processo',
                'verbose_name_plural': 'Projetos/Atividades do Processo',
                'unique_together': {('processo', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='projetos_atividade',
            field=models.ManyToManyField(blank=True, related_name='processos', through='core.ProcessoProjeto', to='core.projetoatividade'),
        ),
        migrations.AddField(
            model_name='processo',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secretaria'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.secretaria'),
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statusprocesso'),
        ),
        migrations.CreateModel(
            name='HistoricalProcesso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_processo_adm', models.CharField(max_length=50)),
                ('numero_edital', models.CharField(blank=True, max_length=50)),
                ('ano_referencia', models.PositiveIntegerField()),
                ('objeto', models.TextField()),
                ('escopo_disputa', models.CharField(choices=[('GLOBAL', 'Global'), ('POR_ITEM', 'Por item'), ('POR_LOTE', 'Por lote')], default='POR_ITEM', max_length=15)),
                ('criterio_julgamento', models.CharField(choices=[('MENOR_PRECO', 'Menor preço'), ('MAIOR_DESCONTO', 'Maior desconto'), ('MELHOR_TECNICA', 'Melhor técnica/Conteúdo artístico'), ('TECNICA_E_PRECO', 'Técnica e preço'), ('MAIOR_LANCE', 'Maior lance (leilão)'), ('MAIOR_RETORNO_ECONOMICO', 'Maior retorno econômico')], default='MENOR_PRECO', max_length=30)),
                ('modo_disputa', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('ABERTO_FECHADO', 'Aberto-Fechado'), ('FECHADO_ABERTO', 'Fechado-Aberto')], max_length=20)),
                ('tipo_objeto', models.CharField(choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('OBRA', 'Obra'), ('SERVICO_ENGENHARIA', 'Serviço de Engenharia')], max_length=25)),
                ('tipo_contratacao', models.CharField(choices=[('REGISTRO_PRECOS', 'Registro de Preços'), ('AQUISICAO', 'Aquisição'), ('AQUISICAO_PARCELADA', 'Aquisição parcelada')], default='AQUISICAO', max_length=25)),
                ('dispensa_com_disputa', models.BooleanField(blank=True, help_text='Apenas para Dispensa: marque se haverá disputa.', null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_hora_abertura', models.DateTimeField(blank=True, null=True)),
                ('inicio_recolhimento_propostas', models.DateTimeField(blank=True, null=True)),
                ('fim_recolhimento_propostas', models.DateTimeField(blank=True, null=True)),
                ('fim_impugnacao_esclarecimentos', models.DateTimeField(blank=True, null=True)),
                ('prazo_manifestacao_recurso_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_manifestacao_recurso_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_recebimento_recursos_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_recebimento_recursos_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_contrarrazoes_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_contrarrazoes_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_homologado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modalidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.modalidade')),
                ('autoridade_competente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.pessoa')),
                ('condutor_processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.pessoa')),
                ('secretaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.secretaria')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.statusprocesso')),
            ],
            options={
                'verbose_name': 'historical processo',
                'verbose_name_plural': 'historical processos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadeorcamentaria')),
            ],
            options={
                'verbose_name': 'Unidade Orçamentária do Processo',
                'verbose_name_plural': 'Unidades Orçamentárias do Processo',
                'unique_together': {('processo', 'unidade')},
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='unidades_orcamentarias',
            field=models.ManyToManyField(blank=True, related_name='processos', through='core.ProcessoUnidade', to='core.unidadeorcamentaria'),
        ),
        migrations.CreateModel(
            name='FornecimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('status_item', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('JULGADO', 'Julgado'), ('ADJUDICADO', 'Adjudicado'), ('HOMOLOGADO', 'Homologado'), ('FRACASSADO', 'Fracassado'), ('DESERTO', 'Deserto'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.processo')),
            ],
            options={
                'ordering': ['processo', 'numero_item'],
                'unique_together': {('processo', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva Orçamentária'), ('PJ', 'Parecer Jurídico'), ('PT', 'Parecer Técnico'), ('OUTROS', 'Outros')], default='OUTROS', max_length=10)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor_referente', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cis_solicitadas', to='core.pessoa')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cis', to='core.processo')),
            ],
            options={
                'ordering': ['-data', 'numero'],
                'unique_together': {('numero', 'data')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together={('numero_processo_adm', 'ano_referencia')},
        ),
    ]
