# Generated by Django 5.2.5 on 2025-08-12 02:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=30)),
                ('escopo', models.CharField(blank=True, max_length=20)),
                ('qtd_itens', models.PositiveIntegerField(default=1)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.processo')),
            ],
            options={
                'ordering': ['processo', 'numero'],
                'unique_together': {('processo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('flag1', models.BooleanField(default=False)),
                ('flag2', models.BooleanField(default=False)),
                ('flag3', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.lote')),
            ],
            options={
                'ordering': ['lote', 'posicao'],
                'unique_together': {('lote', 'posicao', 'fornecedor')},
            },
        ),
    ]
