# Generated by Django 5.2.5 on 2025-08-12 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lote_itemresultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfornecimentoitem',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='historicalfornecimentoitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfornecimentoitem',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='historicalobservacao',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalobservacao',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='historicalobservacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='autoridade_competente',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='condutor_processo',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='secretaria',
        ),
        migrations.RemoveField(
            model_name='historicalprocesso',
            name='status',
        ),
        migrations.AlterModelOptions(
            name='elementodespesa',
            options={'ordering': ['codigo'], 'verbose_name': 'Elemento de despesa', 'verbose_name_plural': 'Elementos de despesa'},
        ),
        migrations.AlterModelOptions(
            name='fonterecurso',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['razao_social']},
        ),
        migrations.AlterModelOptions(
            name='fornecimentoitem',
            options={'ordering': ['numero_item']},
        ),
        migrations.AlterModelOptions(
            name='itemresultado',
            options={'ordering': ['lote__numero', 'posicao']},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='observacao',
            options={'ordering': ['-data_hora']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='processoelemento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processofonte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processoprojeto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processounidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projetoatividade',
            options={'ordering': ['codigo'], 'verbose_name': 'Projeto/Atividade', 'verbose_name_plural': 'Projetos/Atividades'},
        ),
        migrations.AlterModelOptions(
            name='secretaria',
            options={'ordering': ['sigla']},
        ),
        migrations.AlterModelOptions(
            name='statusprocesso',
            options={'ordering': ['nome'], 'verbose_name': 'Status do Processo', 'verbose_name_plural': 'Status dos Processos'},
        ),
        migrations.AlterModelOptions(
            name='unidadeorcamentaria',
            options={'ordering': ['sigla'], 'verbose_name': 'Unidade orçamentária', 'verbose_name_plural': 'Unidades orçamentárias'},
        ),
        migrations.AlterUniqueTogether(
            name='ci',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fonterecurso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemresultado',
            unique_together={('lote', 'posicao')},
        ),
        migrations.AlterUniqueTogether(
            name='processo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='core.lote'),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ci',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ci',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ci',
            name='numero',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ci',
            name='processo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cis', to='core.processo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ci',
            name='status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ci',
            name='tipo',
            field=models.CharField(choices=[('RESERVA', 'Reserva Orçamentária'), ('PARECER_JURIDICO', 'Parecer Jurídico'), ('PARECER_TECNICO', 'Parecer Técnico'), ('OUTROS', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ci',
            name='valor_referente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='elementodespesa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fonterecurso',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fonterecurso',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='numero_item',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='status_item',
            field=models.CharField(blank=True, choices=[('PLANEJADO', 'Planejado'), ('FRACASSADO', 'Fracassado'), ('HOMOLOGADO', 'Homologado')], default='PLANEJADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='unidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemresultado',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='itemresultado',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='lote',
            name='escopo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lote',
            name='qtd_itens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='base_legal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='processo',
            name='autoridade_competente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proc_autoridade', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='condutor_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proc_condutor', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criterio_julgamento',
            field=models.CharField(blank=True, choices=[('MENOR_PRECO', 'Menor preço'), ('MAIOR_DESCONTO', 'Maior desconto'), ('TECNICA_E_PRECO', 'Técnica e preço'), ('MELHOR_TECNICA', 'Melhor técnica')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='dispensa_com_disputa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processo',
            name='escopo_disputa',
            field=models.CharField(choices=[('ITEM', 'Por item'), ('LOTE', 'Por lote'), ('GLOBAL', 'Global')], default='ITEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modalidade'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modo_disputa',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('ABERTO_FECHADO', 'Aberto-Fechado'), ('FECHADO_ABERTO', 'Fechado-Aberto')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_edital',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo_adm',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='processo',
            name='protocolo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='processo',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.secretaria'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statusprocesso'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_contratacao',
            field=models.CharField(blank=True, choices=[('AQUISICAO', 'Aquisição'), ('REGISTRO_PRECO', 'Registro de Preço'), ('AQUISICAO_PARCELADA', 'Aquisição Parcelada')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_objeto',
            field=models.CharField(blank=True, choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço'), ('OBRA', 'Obra'), ('SERVICO_ENG', 'Serviço de Engenharia')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_homologado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='processoelemento',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elementodespesa'),
        ),
        migrations.AlterField(
            model_name='processofonte',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fonterecurso'),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projetoatividade'),
        ),
        migrations.AlterField(
            model_name='processounidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadeorcamentaria'),
        ),
        migrations.AlterField(
            model_name='projetoatividade',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='projetoatividade',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='sigla',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalCI',
        ),
        migrations.DeleteModel(
            name='HistoricalFornecimentoItem',
        ),
        migrations.DeleteModel(
            name='HistoricalObservacao',
        ),
        migrations.DeleteModel(
            name='HistoricalProcesso',
        ),
        migrations.RemoveField(
            model_name='ci',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='elementos_despesa',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='fontes_recursos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_contrarrazoes_horas',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_contrarrazoes_minutos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_manifestacao_recurso_horas',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_manifestacao_recurso_minutos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_recebimento_recursos_horas',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='prazo_recebimento_recursos_minutos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='projetos_atividade',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='unidades_orcamentarias',
        ),
    ]
