# Generated by Django 5.2.5 on 2025-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historicalfornecimentoitem_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lote',
            name='escopo',
            field=models.CharField(blank=True, default='GLOBAL', max_length=50),
        ),
    ]
