# Generated by Django 5.2.5 on 2025-08-12 22:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalci_historicalfornecimentoitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ci',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='ci',
            old_name='descricao',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='historicalci',
            old_name='descricao',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='ci',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ci',
            name='valor_referente',
        ),
        migrations.RemoveField(
            model_name='historicalci',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalci',
            name='valor_referente',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='proposta_final',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='proposta_inicial',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='proposta_final',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='proposta_inicial',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='itemresultado',
            name='classificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemresultado',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemresultado',
            name='microempresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_lance',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('ABERTO_FECHADO', 'Aberto-Fechado'), ('FECHADO_ABERTO', 'Fechado-Aberto')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ci',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ci',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fornecidos', to='core.fornecedor'),
        ),
        migrations.AlterField(
            model_name='historicalci',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalci',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_ci', to='core.ci'),
        ),
        migrations.AlterField(
            model_name='historicalci',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfornecimentoitem',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_item', to='core.fornecimentoitem'),
        ),
        migrations.CreateModel(
            name='HistoricalItemResultado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('flag1', models.BooleanField(default=False)),
                ('flag2', models.BooleanField(default=False)),
                ('flag3', models.BooleanField(default=False)),
                ('microempresa', models.BooleanField(default=False)),
                ('classificado', models.BooleanField(default=False)),
                ('habilitado', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.fornecedor')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_resultado', to='core.itemresultado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lote')),
            ],
            options={
                'verbose_name': 'historical item resultado',
                'verbose_name_plural': 'historical item resultados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('escopo', models.CharField(blank=True, default='GLOBAL', max_length=50)),
                ('qtd_itens', models.PositiveIntegerField(default=0)),
                ('tipo_lance', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('ABERTO_FECHADO', 'Aberto-Fechado'), ('FECHADO_ABERTO', 'Fechado-Aberto')], default='', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_lote', to='core.lote')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.processo')),
            ],
            options={
                'verbose_name': 'historical lote',
                'verbose_name_plural': 'historical lotes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalObservacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_observacao', to='core.observacao')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.processo')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical observacao',
                'verbose_name_plural': 'historical observacaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalProcessoUnidade',
        ),
    ]
