# Generated by Django 5.2.5 on 2025-08-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_historicalitemresultado_flag1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallote',
            name='tipo_lance',
            field=models.CharField(blank=True, choices=[('UNITARIO', 'Unitário'), ('GLOBAL', 'Global'), ('KIT', 'Kit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_lance',
            field=models.CharField(blank=True, choices=[('UNITARIO', 'Unitário'), ('GLOBAL', 'Global'), ('KIT', 'Kit')], default='', max_length=20),
        ),
    ]
