# Generated by script at 2025-08-15 00:35:12
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_historicallote_tipo_lance_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fornecimentoitem",
            unique_together={("processo","lote","numero_item")},
        ),
        migrations.AddConstraint(
            model_name="fornecimentoitem",
            constraint=models.UniqueConstraint(
                fields=("processo","lote","numero_item"),
                name="uq_core_fi_proc_lote_num_item",
            ),
        ),
    ]
