# Generated by Django 5.2.5 on 2025-08-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_unique_item_por_lote'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fornecimentoitem',
            name='uq_core_fi_proc_lote_num_item',
        ),
    ]
