# Generated by Django 5.2.5 on 2025-08-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_fornecimentoitem_uq_core_fi_proc_lote_num_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecimentoitem',
            name='status_item',
            field=models.CharField(blank=True, choices=[('PLANEJADO', 'Planejado'), ('FRACASSADO', 'Fracassado'), ('CANCELADO', 'Cancelado'), ('HOMOLOGADO', 'Homologado')], default='PLANEJADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalfornecimentoitem',
            name='status_item',
            field=models.CharField(blank=True, choices=[('PLANEJADO', 'Planejado'), ('FRACASSADO', 'Fracassado'), ('CANCELADO', 'Cancelado'), ('HOMOLOGADO', 'Homologado')], default='PLANEJADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='criterio_julgamento',
            field=models.CharField(blank=True, choices=[('MENOR_PRECO_POR_ITEM', 'Menor preço por item'), ('MENOR_PRECO_POR_LOTE', 'Menor preço por lote'), ('MENOR_PRECO_GLOBAL', 'Menor preço global'), ('MAIOR_DESCONTO', 'Maior desconto'), ('TECNICA_E_PRECO', 'Técnica e preço'), ('MELHOR_TECNICA', 'Melhor técnica')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='criterio_julgamento',
            field=models.CharField(blank=True, choices=[('MENOR_PRECO_POR_ITEM', 'Menor preço por item'), ('MENOR_PRECO_POR_LOTE', 'Menor preço por lote'), ('MENOR_PRECO_GLOBAL', 'Menor preço global'), ('MAIOR_DESCONTO', 'Maior desconto'), ('TECNICA_E_PRECO', 'Técnica e preço'), ('MELHOR_TECNICA', 'Melhor técnica')], default='', max_length=30),
        ),
    ]
