# Generated by Django 5.2.5 on 2026-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fornecimentoitem_status_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=40)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=80)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('site', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orgaos/logos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orgao/Entidade',
                'verbose_name_plural': 'Orgaos/Entidades',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
    ]
