# Generated by Django 5.2.5 on 2026-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orgaoentidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecimentoitem',
            name='categoria_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='codigo_item_externo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='criterio_julgamento_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='data_resultado_homologacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='numero_controle_pncp',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='ordem_classificacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='pncp_ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='situacao_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='situacao_resultado_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='tipo_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='valor_total_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='valor_total_homologado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='valor_unitario_estimado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='fornecimentoitem',
            name='valor_unitario_homologado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='categoria_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='codigo_item_externo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='criterio_julgamento_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='data_resultado_homologacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='numero_controle_pncp',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='ordem_classificacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='pncp_ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='situacao_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='situacao_resultado_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='tipo_item_pncp',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='valor_total_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='valor_total_homologado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='valor_unitario_estimado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicalfornecimentoitem',
            name='valor_unitario_homologado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
