# Generated by Django 5.2.5 on 2026-03-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fornecimentoitem_categoria_item_pncp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('descricao_padrao', models.TextField()),
                ('unidade_padrao', models.CharField(blank=True, default='', max_length=30)),
                ('especificacao_tecnica', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de catalogo',
                'verbose_name_plural': 'Itens de catalogo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('descricao_snapshot', models.TextField()),
                ('unidade_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('status_consolidado', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_COTACAO', 'Em cotacao'), ('HOMOLOGADO', 'Homologado'), ('FRACASSADO', 'Fracassado'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20)),
                ('valor_referencia_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_referencia_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_homologado_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_homologado_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('conflito_lote', models.BooleanField(default=False)),
                ('pncp_ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor_homologado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_homologados_processo', to='core.fornecedor')),
                ('item_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_processo', to='core.itemcatalogo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_canonicos', to='core.processo')),
            ],
            options={
                'ordering': ['processo_id', 'numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoLoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_vinculados', to='core.processoitem')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_canonicos', to='core.lote')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_itens_canonicos', to='core.processo')),
            ],
            options={
                'ordering': ['processo_id', 'lote__numero', 'item__numero_item'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorDocumentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('PNCP', 'PNCP'), ('BLL', 'BLL'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('documento_digits', models.CharField(blank=True, default='', max_length=20)),
                ('identificador_externo', models.CharField(blank=True, default='', max_length=120)),
                ('payload_resumo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_externos', to='core.fornecedor')),
            ],
            options={
                'ordering': ['origem', 'documento_digits', 'id'],
                'unique_together': {('origem', 'documento_digits'), ('origem', 'identificador_externo')},
            },
        ),
        migrations.AddIndex(
            model_name='processoitem',
            index=models.Index(fields=['processo', 'status_consolidado'], name='core_proces_process_cace45_idx'),
        ),
        migrations.AddIndex(
            model_name='processoitem',
            index=models.Index(fields=['numero_item'], name='core_proces_numero__6fddeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processoitem',
            unique_together={('processo', 'numero_item')},
        ),
        migrations.AddIndex(
            model_name='processoloteitem',
            index=models.Index(fields=['processo', 'item'], name='core_proces_process_a512f2_idx'),
        ),
        migrations.AddIndex(
            model_name='processoloteitem',
            index=models.Index(fields=['processo', 'lote'], name='core_proces_process_d1f7aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processoloteitem',
            unique_together={('lote', 'item')},
        ),
    ]
