# Generated by Django 5.2.5 on 2026-03-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_itemcatalogo_processoitem_processoloteitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoItemResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('OFERTA', 'Oferta'), ('RESULTADO_LOTE', 'Resultado do lote'), ('ITEM_LEGADO', 'Item legado'), ('PNCP', 'PNCP'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('chave_origem', models.CharField(blank=True, default='', max_length=160)),
                ('status_resultado', models.CharField(choices=[('CLASSIFICADO', 'Classificado'), ('DESCLASSIFICADO', 'Desclassificado'), ('INABILITADO', 'Inabilitado'), ('VENCEDOR', 'Vencedor'), ('HOMOLOGADO', 'Homologado'), ('FRACASSADO', 'Fracassado'), ('CANCELADO', 'Cancelado')], default='CLASSIFICADO', max_length=20)),
                ('classificacao', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('data_resultado', models.DateField(blank=True, null=True)),
                ('situacao_texto', models.CharField(blank=True, default='', max_length=140)),
                ('payload_resumo', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_itens_processo', to='core.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_itens_canonicos', to='core.processo')),
                ('processo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.processoitem')),
            ],
            options={
                'ordering': ['processo_id', 'processo_item__numero_item', 'classificacao', 'id'],
                'indexes': [models.Index(fields=['processo', 'origem'], name='core_proces_process_4a5026_idx'), models.Index(fields=['processo_item', 'status_resultado'], name='core_proces_process_04baa8_idx'), models.Index(fields=['fornecedor'], name='core_proces_fornece_7fa44d_idx')],
                'unique_together': {('processo_item', 'origem', 'chave_origem')},
            },
        ),
    ]
