# Generated by Django 5.2.5 on 2026-03-12 02:27

from django.db import migrations, models


def _parse_seq(numero, ano_ref):
    texto = str(numero or "").strip()
    if "/" not in texto:
        return 0
    partes = [p.strip() for p in texto.split("/", 1)]
    if len(partes) != 2:
        return 0
    if not partes[0].isdigit() or not partes[1].isdigit():
        return 0
    if int(partes[1]) != int(ano_ref):
        return 0
    return int(partes[0])


def preencher_numero_sirel_existente(apps, schema_editor):
    Processo = apps.get_model("core", "Processo")
    anos = (
        Processo.objects
        .exclude(ano_referencia__isnull=True)
        .values_list("ano_referencia", flat=True)
        .distinct()
        .order_by("ano_referencia")
    )
    for ano in anos:
        sequencial = 0
        updates = []
        queryset = Processo.objects.filter(ano_referencia=ano).order_by("criado_em", "id")
        for processo in queryset.iterator():
            atual = (getattr(processo, "numero_processo_sirel", "") or "").strip()
            atual_seq = _parse_seq(atual, ano)
            if atual_seq > 0:
                sequencial = max(sequencial, atual_seq)
                continue
            sequencial += 1
            processo.numero_processo_sirel = f"{sequencial:04d}/{int(ano)}"
            updates.append(processo)
        if updates:
            Processo.objects.bulk_update(updates, ["numero_processo_sirel"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_processoitemresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='numero_processo_sirel',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero_processo_sirel',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunPython(preencher_numero_sirel_existente, noop_reverse),
    ]
