# Generated by Django 5.2.5 on 2026-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historicalprocesso_numero_processo_sirel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallote',
            name='exclusivo_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='garantia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='intervalo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='local_entrega',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='melhor_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='historicallote',
            name='vencedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='identificador_bll',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='link_bll',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='promotor_bll',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lote',
            name='exclusivo_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='garantia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lote',
            name='intervalo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='lote',
            name='local_entrega',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lote',
            name='melhor_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='lote',
            name='valor_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='lote',
            name='vencedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processo',
            name='identificador_bll',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='processo',
            name='link_bll',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='processo',
            name='promotor_bll',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
