# Generated by Django 5.2.5 on 2025-08-14 23:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_historicallote_tipo_lance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('proposta_inicial', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('proposta_final', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('CLASSIFICADO', 'Classificado'), ('DESCLASSIFICADO', 'Desclassificado'), ('INABILITADO', 'Inabilitado'), ('VENCEDOR', 'Vencedor')], default='CLASSIFICADO', max_length=20)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_itens', to='core.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.fornecimentoitem')),
            ],
            options={
                'ordering': ['item__numero_item', 'classificacao'],
                'unique_together': {('item', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemOferta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('classificacao', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('proposta_inicial', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('proposta_final', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('CLASSIFICADO', 'Classificado'), ('DESCLASSIFICADO', 'Desclassificado'), ('INABILITADO', 'Inabilitado'), ('VENCEDOR', 'Vencedor')], default='CLASSIFICADO', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.fornecedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.fornecimentoitem')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_oferta', to='ofertas.itemoferta')),
            ],
            options={
                'verbose_name': 'historical item oferta',
                'verbose_name_plural': 'historical item ofertas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
