# Generated by Django 5.2.5 on 2025-08-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_historicalitemresultado_flag1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EDITAL', 'Edital'), ('AVISO', 'Aviso de Licitação'), ('TERMO_AUTUACAO', 'Termo de Autuação'), ('TERMO_AUTORIZACAO', 'Termo de Autorização'), ('PARECER', 'Parecer Jurídico'), ('OUTROS', 'Outros')], default='OUTROS', max_length=32)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.processo')),
            ],
        ),
    ]
