# -*- coding: utf-8 -*-
"""
Gera uma migração para tornar (processo, lote, numero_item) únicos em core.FornecimentoItem.

Como usar (na raiz do projeto, onde está manage.py):
    python scripts/gerar_migracao_unique_por_lote.py
    python manage.py makemigrations
    python manage.py migrate

O script:
- Descobre a última migração do app "core"
- Cria uma nova migração sequencial com dependência correta
- Define unique_together = {('processo','lote','numero_item')}
- Também adiciona um UniqueConstraint nomeado (por segurança)

Compatível com Django 3.x/4.x/5.x
"""
from pathlib import Path
import re
import sys
from datetime import datetime

APP = "core"
MODEL_NAME = "fornecimentoitem"  # lowercase

project_root = Path(__file__).resolve().parents[1]
migrations_dir = project_root / APP / "migrations"
if not migrations_dir.exists():
    print(f"ERRO: pasta de migrações não encontrada em {migrations_dir}")
    sys.exit(1)

# encontra a última migração [0-9]{4}_*.py
mig_files = sorted([p for p in migrations_dir.glob("[0-9][0-9][0-9][0-9]_*.py")])
if not mig_files:
    print("ERRO: não foram encontradas migrações em core/migrations. Rode 'python manage.py makemigrations core' primeiro.")
    sys.exit(1)

last = mig_files[-1].name[:-3]  # sem .py
m = re.match(r"(?P<num>\d{4})_(?P<slug>.+)", last)
if not m:
    print(f"ERRO: arquivo de migração inesperado: {last}")
    sys.exit(1)

next_num = int(m.group("num")) + 1
new_name = f"{next_num:04d}_unique_item_por_lote.py"
new_path = migrations_dir / new_name

generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
content = """# Generated by script at {generated_at}
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("{APP}", "{last}"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="{MODEL_NAME}",
            unique_together={{("processo","lote","numero_item")}},
        ),
        migrations.AddConstraint(
            model_name="{MODEL_NAME}",
            constraint=models.UniqueConstraint(
                fields=("processo","lote","numero_item"),
                name="uq_core_fi_proc_lote_num_item",
            ),
        ),
    ]
""".format(generated_at=generated_at, APP=APP, last=last, MODEL_NAME=MODEL_NAME)

new_path.write_text(content, encoding="utf-8")
print(f"OK: criada migração {new_path}")
print("Agora rode:  python manage.py makemigrations && python manage.py migrate")
