# Generated by Django 5.2.5 on 2026-03-10 04:16

import django.db.models.deletion
from django.db import migrations, models


def migrar_tipo_para_especie(apps, schema_editor):
    PlanejamentoDFD = apps.get_model('workflow', 'PlanejamentoDFD')
    PlanejamentoDFD.objects.filter(tipo_contratacao_planejamento='OBRA_SERV_ENG').update(
        especie_contratacao='OBRA_SERV_ENG',
        tipo_contratacao_planejamento='AQUISICAO',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fornecimentoitem_status_item_and_more'),
        ('workflow', '0002_planejamento_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentodfd',
            name='especie_contratacao',
            field=models.CharField(choices=[('MATERIAL', 'Materiais'), ('SERVICO', 'Serviços'), ('MATERIAL_SERVICO', 'Materiais/Serviços'), ('OBRA_SERV_ENG', 'Obra/Serv. de Engenharia')], default='MATERIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='planejamentodfd',
            name='responsavel_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfds_responsavel', to='core.pessoa'),
        ),
        migrations.RunPython(migrar_tipo_para_especie, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='planejamentodfd',
            name='tipo_contratacao_planejamento',
            field=models.CharField(choices=[('SRP', 'SRP'), ('AQUISICAO', 'Aquisição')], default='AQUISICAO', max_length=30),
        ),
    ]
