# Generated by Django 5.2.5 on 2026-03-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orgaoentidade'),
        ('workflow', '0003_planejamentodfd_especie_contratacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etpcotacaofonte',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_etp', to='core.fornecedor'),
        ),
    ]
