# Generated by Django 5.2.5 on 2026-03-10 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orgaoentidade'),
        ('workflow', '0004_etpcotacaofonte_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_origem', models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração')], max_length=30)),
                ('modulo_destino', models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração')], max_length=30)),
                ('ano_exercicio', models.PositiveIntegerField()),
                ('numero_sequencial', models.PositiveIntegerField()),
                ('data_comunicacao', models.DateField(default=django.utils.timezone.now)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('responsavel_envio', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes_internas_criadas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes_internas', to='core.processo')),
                ('processo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes_referenciadas', to='core.processo')),
                ('signatarios', models.ManyToManyField(blank=True, related_name='comunicacoes_internas', to='core.pessoa')),
            ],
            options={
                'ordering': ['-ano_exercicio', '-numero_sequencial', '-id'],
                'constraints': [models.UniqueConstraint(fields=('modulo_origem', 'ano_exercicio', 'numero_sequencial'), name='uq_ci_numero_por_modulo_ano')],
            },
        ),
    ]
