# Generated by Django 5.2.5 on 2026-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_comunicacaointerna'),
    ]

    operations = [
        migrations.AddField(
            model_name='etpcotacaofonte',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
