# Generated by Django 5.2.5 on 2026-03-10 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orgaoentidade'),
        ('workflow', '0006_etpcotacaofonte_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNCPContratacaoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle_pncp', models.CharField(max_length=80, unique=True)),
                ('numero_compra', models.CharField(blank=True, default='', max_length=50)),
                ('ano_compra', models.PositiveIntegerField(blank=True, null=True)),
                ('processo_origem', models.CharField(blank=True, default='', max_length=80)),
                ('tipo_instrumento_convocatorio_id', models.IntegerField(blank=True, null=True)),
                ('tipo_instrumento_convocatorio_nome', models.CharField(blank=True, default='', max_length=120)),
                ('modalidade_id', models.IntegerField(blank=True, null=True)),
                ('modalidade_nome', models.CharField(blank=True, default='', max_length=120)),
                ('modo_disputa_id', models.IntegerField(blank=True, null=True)),
                ('modo_disputa_nome', models.CharField(blank=True, default='', max_length=120)),
                ('criterio_julgamento_id', models.IntegerField(blank=True, null=True)),
                ('criterio_julgamento_nome', models.CharField(blank=True, default='', max_length=120)),
                ('situacao_compra_id', models.IntegerField(blank=True, null=True)),
                ('situacao_compra_nome', models.CharField(blank=True, default='', max_length=120)),
                ('objeto_compra', models.TextField(blank=True, default='')),
                ('informacao_complementar', models.TextField(blank=True, default='')),
                ('srp', models.BooleanField(default=False)),
                ('amparo_legal_codigo', models.IntegerField(blank=True, null=True)),
                ('amparo_legal_nome', models.CharField(blank=True, default='', max_length=255)),
                ('amparo_legal_descricao', models.TextField(blank=True, default='')),
                ('valor_total_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total_homologado', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('data_abertura_proposta', models.DateTimeField(blank=True, null=True)),
                ('data_encerramento_proposta', models.DateTimeField(blank=True, null=True)),
                ('data_publicacao_pncp', models.DateField(blank=True, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateField(blank=True, null=True)),
                ('sequencial_compra', models.IntegerField(blank=True, null=True)),
                ('orgao_cnpj', models.CharField(blank=True, default='', max_length=20)),
                ('orgao_razao_social', models.CharField(blank=True, default='', max_length=255)),
                ('orgao_poder_id', models.CharField(blank=True, default='', max_length=3)),
                ('orgao_esfera_id', models.CharField(blank=True, default='', max_length=3)),
                ('unidade_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('unidade_nome', models.CharField(blank=True, default='', max_length=255)),
                ('unidade_codigo_ibge', models.CharField(blank=True, default='', max_length=12)),
                ('unidade_municipio_nome', models.CharField(blank=True, default='', max_length=120)),
                ('unidade_uf_sigla', models.CharField(blank=True, default='', max_length=2)),
                ('unidade_uf_nome', models.CharField(blank=True, default='', max_length=120)),
                ('orgao_subrogado_cnpj', models.CharField(blank=True, default='', max_length=20)),
                ('orgao_subrogado_razao_social', models.CharField(blank=True, default='', max_length=255)),
                ('orgao_subrogado_poder_id', models.CharField(blank=True, default='', max_length=3)),
                ('orgao_subrogado_esfera_id', models.CharField(blank=True, default='', max_length=3)),
                ('unidade_subrogada_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('unidade_subrogada_nome', models.CharField(blank=True, default='', max_length=255)),
                ('unidade_subrogada_codigo_ibge', models.CharField(blank=True, default='', max_length=12)),
                ('unidade_subrogada_municipio_nome', models.CharField(blank=True, default='', max_length=120)),
                ('unidade_subrogada_uf_sigla', models.CharField(blank=True, default='', max_length=2)),
                ('unidade_subrogada_uf_nome', models.CharField(blank=True, default='', max_length=120)),
                ('usuario_nome', models.CharField(blank=True, default='', max_length=255)),
                ('link_sistema_origem', models.URLField(blank=True, default='')),
                ('justificativa_presencial', models.TextField(blank=True, default='')),
                ('payload_completo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pncp_snapshot', to='core.processo')),
            ],
            options={
                'verbose_name': 'Snapshot PNCP da contratacao',
                'verbose_name_plural': 'Snapshots PNCP das contratacoes',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
    ]
