# Generated by Django 5.2.5 on 2026-03-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_pncpcontratacaosnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('inicio_intervalo', models.TimeField(blank=True, null=True)),
                ('fim_intervalo', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('nao_trabalhado_util', models.BooleanField(default=False)),
                ('justificativa_nao_trabalhado', models.TextField(blank=True, default='')),
                ('justificativa_horas_extras', models.TextField(blank=True, default='')),
                ('observacao', models.TextField(blank=True, default='')),
                ('horas_trabalhadas_minutos', models.PositiveIntegerField(default=0)),
                ('horas_extras_minutos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de frequencia',
                'verbose_name_plural': 'Registros de frequencia',
                'ordering': ['-data', '-id'],
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
