# Generated by Django 5.2.5 on 2026-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_alter_integracaoprocesso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integracaoprocesso',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Log de integração', 'verbose_name_plural': 'Logs de integração'},
        ),
        migrations.AlterModelOptions(
            name='processomovimentacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Movimentação do processo', 'verbose_name_plural': 'Movimentações do processo'},
        ),
        migrations.AlterField(
            model_name='comunicacaointerna',
            name='modulo_destino',
            field=models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comunicacaointerna',
            name='modulo_origem',
            field=models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentoprocessoworkflow',
            name='modulo',
            field=models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='etpcotacaofonte',
            name='tipo_fonte',
            field=models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('BANCO_PRECOS', 'Banco de preços'), ('SITE', 'Sítio oficial'), ('OUTRO', 'Outro')], default='FORNECEDOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='etpplanejamento',
            name='metodologia_cotacao',
            field=models.CharField(choices=[('MEDIA', 'Média Aritmética'), ('MEDIANA', 'Mediana'), ('MENOR', 'Menor Preço')], default='MEDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='integracaoprocesso',
            name='tipo',
            field=models.CharField(choices=[('PNCP', 'PNCP'), ('BLL_IMPORTACAO', 'BLL Importação'), ('BLL_EXPORTACAO', 'BLL Exportação')], max_length=30),
        ),
        migrations.AlterField(
            model_name='planejamentodfd',
            name='especie_contratacao',
            field=models.CharField(choices=[('MATERIAL', 'Materiais'), ('SERVICO', 'Serviços'), ('MATERIAL_SERVICO', 'Materiais/Serviços'), ('OBRA_SERV_ENG', 'Obra/Serv. de Engenharia')], default='MATERIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='planejamentodfd',
            name='modalidade_pretendida',
            field=models.CharField(choices=[('PREGAO', 'Pregão'), ('DISPENSA_ELETRONICA', 'Dispensa Eletrônica'), ('DISPENSA_SIMPLIFICADA', 'Dispensa Simplificada'), ('INEXIGIBILIDADE', 'Inexigibilidade'), ('CONCORRENCIA', 'Concorrência'), ('CREDENCIAMENTO', 'Credenciamento'), ('ADESAO_ARP', 'Adesão a Ata de Registro de Preços')], default='PREGAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='planejamentodfd',
            name='tipo_contratacao_planejamento',
            field=models.CharField(choices=[('SRP', 'SRP'), ('AQUISICAO', 'Aquisição')], default='AQUISICAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='processomovimentacao',
            name='modulo_destino',
            field=models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processomovimentacao',
            name='modulo_origem',
            field=models.CharField(blank=True, choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='processoworkflow',
            name='modulo_atual',
            field=models.CharField(choices=[('PLANEJAMENTO', '1 - Planejamento'), ('COMPRAS', '2 - Compras'), ('LICITACAO', '3 - Licitação'), ('PROCURADORIA', '4 - Procuradoria'), ('CONTROLADORIA', '5 - Controladoria'), ('CONTRATOS', '6 - Contratos'), ('DASHBOARDS', '7 - Dashboards'), ('DOCUMENTOS', '8 - Documentos'), ('INTEGRACAO', '9 - Integração'), ('FREQUENCIA', '10 - Frequência')], default='PLANEJAMENTO', max_length=30),
        ),
        migrations.AlterField(
            model_name='processoworkflow',
            name='situacao',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando ação externa'), ('CONCLUIDO', 'Concluído'), ('SUSPENSO', 'Suspenso')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='trplanejamento',
            name='criterio_julgamento',
            field=models.CharField(choices=[('MENOR_PRECO_GLOBAL', 'Menor preço global'), ('MENOR_PRECO_POR_ITEM', 'Menor preço por item'), ('MENOR_PRECO_POR_LOTE', 'Menor preço por lote'), ('MAIOR_PERCENTUAL_DESCONTO', 'Maior percentual de desconto'), ('MENOR_TAXA_ADMINISTRATIVA', 'Menor taxa administrativa')], default='MENOR_PRECO_POR_ITEM', max_length=40),
        ),
    ]
