# Generated by Django 5.2.5 on 2026-03-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_integracaoprocesso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequenciaregistro',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Registro de frequência', 'verbose_name_plural': 'Registros de frequência'},
        ),
        migrations.AlterModelOptions(
            name='pncpcontratacaosnapshot',
            options={'ordering': ['-atualizado_em', '-id'], 'verbose_name': 'Snapshot PNCP da contratação', 'verbose_name_plural': 'Snapshots PNCP das contratações'},
        ),
    ]
