# Generated by Django 5.2.6 on 2026-03-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_processoitemresultado'),
        ('workflow', '0010_alter_frequenciaregistro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNCPDetalhamentoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle_pncp', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluido'), ('PARCIAL', 'Parcial'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('prioridade', models.PositiveIntegerField(default=100)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('origem', models.CharField(blank=True, default='IMPORTACAO_LOTE', max_length=30)),
                ('payload_resumo', models.JSONField(blank=True, default=dict)),
                ('agendado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pncp_detalhamento_fila', to='core.processo')),
            ],
            options={
                'verbose_name': 'Fila de detalhamento PNCP',
                'verbose_name_plural': 'Fila de detalhamento PNCP',
                'ordering': ['prioridade', '-agendado_em'],
            },
        ),
    ]
